#!/bin/bash

if [ -z $1 ] ; then
    echo No executable provided >&2
    exit 1
fi

echo Running tests...

output="$(./$1)"
retval=$?

if ! echo "$output" | grep -q "Finised [0-9]+ tests successfully" ; then
    printf "Tests failed:\n%s\n\n" "$output"
else
    printf "%s\n\n", "$output"
fi

printf "Process returned %s\n", "$retval"
exit $retval
