#!/bin/bash

if [ -z $1 ] ; then
    echo No executable provided >&2
    exit 1
fi

if [ "$2" == "--leak" ] ; then
    printf "Running leak test...\n\n"
    output="$(valgrind --tool=memcheck ./$1 2>&1 > /dev/null)"

    if ! echo "$output" | grep -q "All heap blocks were freed" ; then
        printf "Memory leak detected:\n%s\n" "$output"
        exit 1
    else
        printf "%s\n\nNo leaks detected\n" "$output"
    fi
    exit 0
fi

echo Running tests...

output="$(./$1)"
retval=$?

if ! echo "$output" | grep -q "Finised [0-9]+ tests successfully" ; then
    printf "Tests failed:\n%s\n\n" "$output"
else
    printf "%s\n\n", "$output"
fi

printf "Process returned %s\n", "$retval"
exit $retval
